apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-helm-flux2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: poc-helm-flux2
  template:
    metadata:
      labels:
        app: poc-helm-flux2
    spec:
      containers:
      - name: hello-kubernetes
        image: artifactory.wdc.com:6569/bdap-edge-fieldlogs/sftp-fieldlogs-collector:2.0.4
        command: ["java"]
        args: ["-cp", "/app/resources:/app/classes:/app/libs/*", "com.wdc.bdp.edge.fieldlogs.config.FieldLogServer"]
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE  
          value: Hello from the first deployment!
        - name: SCHEDULED_INTERVAL
          value: "120000"
        - name: COLLECTOR_TYPE
          value: REPAIR
        - name: ENV
          value: dev
        - name: CLUSTER
          value: dev

