apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-helm-flux2
spec:
  replicas: 1
  minReadySeconds: 3
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: poc-helm-flux2
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9797"
      labels:
        app: poc-helm-flux2
    spec:
      containers:
      - name: poc-helm-flux2
        image: artifactory.wdc.com:6569/bdap-edge-fieldlogs/sftp-fieldlogs-collector:2.0.4
        command: ["java"]
        args: ["-cp", "/app/resources:/app/classes:/app/libs/*", "com.wdc.bdp.edge.fieldlogs.config.FieldLogServer"]
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 9898
          protocol: TCP
        - name: http-metrics
          containerPort: 9797
          protocol: TCP
        - name: grpc
          containerPort: 9999
          protocol: TCP
        env:
        - name: PODINFO_UI_COLOR
          value: "#34577c"
        - name: SCHEDULED_INTERVAL
          value: "120000"
        - name: COLLECTOR_TYPE
          value: REPAIR
        - name: ENV
          value: dev
        - name: CLUSTER
          value: dev
        resources:
          limits:
            cpu: 2000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 64Mi
